-- MySQL Script generated by MySQL Workbench
-- Fri Sep 20 07:56:35 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema venda
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema venda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `venda` DEFAULT CHARACTER SET utf8 ;
USE `venda` ;

-- -----------------------------------------------------
-- Table `venda`.`CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda`.`CATEGORIA` (
  `idCATEGORIA` INT NOT NULL,
  `dsCATEGORIA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCATEGORIA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venda`.`PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda`.`PRODUTO` (
  `idPRODUTO` INT NOT NULL,
  `dsPRODUTO` VARCHAR(45) NOT NULL,
  `preco` FLOAT NULL,
  `qtdade` INT NULL,
  `foto` LONGBLOB NULL,
  `CATEGORIA_idCATEGORIA` INT NOT NULL, -- chave estrangeira
  PRIMARY KEY (`idPRODUTO`),
  -- INDEX `fk_PRODUTO_CATEGORIA_idx` (`CATEGORIA_idCATEGORIA` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUTO_CATEGORIA`
    FOREIGN KEY (`CATEGORIA_idCATEGORIA`)
    REFERENCES `venda`.`CATEGORIA` (`idCATEGORIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venda`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda`.`CLIENTE` (
  `idCLIENTE` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCLIENTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venda`.`PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda`.`PEDIDO` (
  `idPEDIDO` INT NOT NULL,
  `data` DATE NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `sessao` VARCHAR(45) NOT NULL,
  `CLIENTE_idCLIENTE` INT NOT NULL, -- chave estrangeira
  PRIMARY KEY (`idPEDIDO`),
  -- INDEX `fk_PEDIDO_CLIENTE1_idx` (`CLIENTE_idCLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_idCLIENTE`)
    REFERENCES `venda`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venda`.`PEDIDOITENS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda`.`PEDIDOITENS` (
  `idPEDIDOITENS` INT NOT NULL,
  `qtade` INT NOT NULL,
  `preco` FLOAT NOT NULL,
  `total` FLOAT NOT NULL,
  `PRODUTO_idPRODUTO` INT NOT NULL, --  chave estrangeira
  `PEDIDO_idPEDIDO` INT NOT NULL,   -- chave estrangeira
  PRIMARY KEY (`idPEDIDOITENS`),
  -- INDEX `fk_PEDIDOITENS_PRODUTO1_idx` (`PRODUTO_idPRODUTO` ASC) VISIBLE,
  -- INDEX `fk_PEDIDOITENS_PEDIDO1_idx` (`PEDIDO_idPEDIDO` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDOITENS_PRODUTO1`
    FOREIGN KEY (`PRODUTO_idPRODUTO`)
    REFERENCES `mydb`.`PRODUTO` (`idPRODUTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDOITENS_PEDIDO1`
    FOREIGN KEY (`PEDIDO_idPEDIDO`)
    REFERENCES `mydb`.`PEDIDO` (`idPEDIDO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
