-- MySQL Script generated by MySQL Workbench
-- Fri Sep 13 08:09:45 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema capacitacao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema capacitacao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `capacitacao` DEFAULT CHARACTER SET utf8 ;
USE `capacitacao` ;

-- -----------------------------------------------------
-- Table `capacitacao`.`instrutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capacitacao`.`instrutor` (
  `idinstrutor` 	INT NOT NULL,
  `nome`			VARCHAR(100) NOT NULL,
  `email` 			VARCHAR(100) NOT NULL,
  `valorHora` 		DOUBLE NOT NULL,
  `certificados` 	VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idinstrutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capacitacao`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capacitacao`.`curso` (
  `idcurso` 		INT NOT NULL,
  `nome` 			VARCHAR(100) NOT NULL,
  `requisito` 		VARCHAR(100) NOT NULL,
  `cargaHoraria` 	DOUBLE NOT NULL,
  `preco` 			DOUBLE NOT NULL,
  PRIMARY KEY (`idcurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capacitacao`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capacitacao`.`aluno` (
  `idaluno` 		INT NOT NULL,
  `nome` 			VARCHAR(100) NOT NULL,
  `cpf` 			VARCHAR(15) NOT NULL,
  `dataNasc` 		DATE NOT NULL,
  `telefone` 		CHAR(14) NOT NULL,
  `email` 			VARCHAR(100) NULL,
  PRIMARY KEY (`idaluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capacitacao`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capacitacao`.`turma` (
  `idturma` 		INT NOT NULL,
  `cargaHoraria` 	DOUBLE NOT NULL,
  `dataInicial` 	DATE NOT NULL,
  `dataFinal` 		DATE NOT NULL,
  `instrutor_idinstrutor` INT NOT NULL, -- chave estrangeira
  `curso_idcurso` 	INT NOT NULL,       -- chave estrangeira
  PRIMARY KEY (`idturma`, `instrutor_idinstrutor`, `curso_idcurso`),
  -- INDEX `fk_turma_instrutor_idx` (`instrutor_idinstrutor` ASC) VISIBLE,
  -- INDEX `fk_turma_curso1_idx` (`curso_idcurso` ASC) VISIBLE,
  CONSTRAINT `fk_turma_instrutor`
    FOREIGN KEY (`instrutor_idinstrutor`)
    REFERENCES `capacitacao`.`instrutor` (`idinstrutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_curso1`
    FOREIGN KEY (`curso_idcurso`)
    REFERENCES `capacitacao`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capacitacao`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capacitacao`.`matricula` (
  `idmatricula` 	INT NOT NULL,
  `dataMatricula` 	DATE NOT NULL,
  `matriculacol` 	VARCHAR(45) NULL,
  `aluno_idaluno` 	INT NOT NULL, -- chave estrangeira
  `turma_idturma` 	INT NOT NULL, -- chave estrangeira
  PRIMARY KEY (`idmatricula`),
  -- INDEX `fk_matricula_aluno1_idx` (`aluno_idaluno` ASC) VISIBLE,
  -- INDEX `fk_matricula_turma1_idx` (`turma_idturma` ASC) VISIBLE,
  CONSTRAINT `fk_matricula_aluno1`
    FOREIGN KEY (`aluno_idaluno`)
    REFERENCES `capacitacao`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_turma1`
    FOREIGN KEY (`turma_idturma`)
    REFERENCES `capacitacao`.`turma` (`idturma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
